server:
  port: 8111
  servlet:
    context-path: /pay/
spring:
  application:
    name: alipay




  thymeleaf:
    cache: false
    enabled: true

alipay:
  app_id: 2016092800613850
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkMB5JRicjTD2UiaDPvRV0Gse4xJt6woj20EHmSoYN4DPq7skJNVevlf9PXZH1X1r8Tb2trh/XJWmTb+esLBUFAI2tjpprmik/eh8tMwPbeQIb5kzKvC1m/Veuh7h5XeWJJJNO7dPEhBLTqtupvsyIbIZ+HyS+gWr7QAqT001w+ac5m9Xn3JT2P+o+DwUsiyp6omXSK5w27mMIXeODEHtZQ0WfXJLUWZS/E3pUhkKazAcso0oTjlej8pMgusvqPIcnZ3nz61xWRud5jwlrdqI86tQjVFCsoSxN7QlgCmVSkPpNez0Kjeic5sxuz1OZDZAMBq7NLuayasLB8VdiaUa3AgMBAAECggEAQsaHKsnrVQHG8chfrN18AjJ6E/1yNqUzyx28D4szpiUPOHdRL/uP5AufQIoPuLnFaWO8xwxQStIedCZJFM8A5X3qITIkP6r9J6HlWB6tbO90GiC6DqIl3QMgTA1Ky6GSnwpPFwTG4d/NQGT23byJttpcgKLt8MT126WaJ7ECh/V6QR/jyvDxpDq1V3AuZrHoNKEh45teVGKzVvB7oGlkrrO26I3qP7MeXXxRe4KsGOejkNf9xXHYniDlgsKBpi12+tXZw7FLtFBY3ytiPto7OyzdlYgQMr9LrYwUxwwNndZmaBH5STwXr2YJ5oYKWvRCDUWGukJAEGgPOQVV0ZJoAQKBgQDXqlFuDKEwmXlbRITPCNIPzNl5JCeKQt63lPIqN3Z9hdTsdoyOklloTnQbcSIwuX1/JRf3bbEV/l2SVIio081dTmfcTZxIwo6YxDO/Jbi1LttlqhtqiFvvaVA50+Ej6qgSrSLZpWmiFOltt3o7LpAIwhqaWoeCw5Q3oUBnaYFyAQKBgQDC5Sdvr4satA77I9LhkpNyGCvdocSB+7wmrkxoUf0F81B7WV2FxPl8+l1W7/PCAzuMWM2WomkKZs+wwatI+wzvpCCD6e8dDQZraVf4+iY//IV7yBkrCXqFF461Rx2W1HXb534Bg1NAj+MoAM7QrfdS6PVldG5RI9+OXRk3NdDItwKBgQDXNue74m6YiQ9JvL6rvCmkCtCayzGKD+EhYkmnR2G/MWah8kuhmvoN1PyYxfVQmkpaLzITgCtPv16xQBqAH5y4mB2dAvYKxdx3JpRdE8+XPwNCGNbzINBdwcKFcqMhrHG88Xntp9waGrQ3APnBRV4G32ycy+qe2311Zj1W9TpwAQKBgB0HyUIHoe7OV1TtVyImlTPvickvqXe7KaGRYOxBGjFituBIxXeBibAmEvU6NNL3bE1RhP4lHwRfoBwyHPN4ActIZVeA5w8qu4QQYvxBNqVdVfzEJ4uTk95zTdyOxUeMSioBZ3GOQD5jsHBq/mNzJl4BOVxtZWlMsKYiE/l3WKwtAoGAbLq6HUg6bzJwD32GlLLjaLgkafcntI5q2cEXPzBC2xEv+bDM8dOEOlH2sSzMERg61gVH/IiBNVjTo3uzyRncExmV4tHoPJzeEk4BSB4jvdJ9zuZxydn/5xPzgUn5jExqxt+YAB2K5JMnjvzD7Cig0f7AjqitOxfwUWB9fRurs74=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvalKOEm8NC5D8zkk9UltwOrK1tDCmY5moMS8/h7T7rd4A5OqLXtDaarIYupM78Sg2fP7ql8OWP0TWRNmnTp+YbRD85UlFvHMZcuDBDMOJH2Jq61irQnxlyIL75uHW/YpiYWmdYvYWZu48jAwX4o+2YVrNyQIt1f8+4tEpEpcQfZMRaFBLKWJLZaaKMyjpa56WvIq1fz4qG1VTHMLPrs+RJZtj/szSpKsmkkQPAyfHDq3tchERl1UHdn4h1zjLxxtcN5zXDFvPXtixychBG5g7ZZh+h+ALAGSbliboTEXTljP8BonsNSMepNEYr7/zsxqi8YKQUb1ISNO9n8lce+hywIDAQAB
  notify_url: http://zhaoxiaqinghui.top/pay/aliPayNotice
  return_url: http://zhaoxiaqinghui.top/pay/aliPayNotice
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  seller_email: 17633947939@163.com

wxpay:
  app_id:
  mch_id:
  key:
  package_sign:
  refund_url:
  transfer_url:
  web_root_url: